version: '3.7'

networks:
  network:
    driver: bridge

services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-clientes
    hostname: mysql-clientes
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clientesdb
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network
    restart: always

volumes:
  mysql-data:
